package ui;

public class uiiPi extends javax.swing.JFrame {

	/**
	 * Creates new form uiiPi
	 */
	public uiiPi() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		nodesTextField = new javax.swing.JTextField();
		resultPiLabel = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		loadCSVButton = new javax.swing.JToggleButton();
		calculatePiButton = new javax.swing.JToggleButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		pointsTextField = new javax.swing.JTextField();
		seedTextField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		resultPiLabel.setText("Pi =");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel6.setText("Calculo de PI con el Metodo de Simulacion de Montecarlo");
		jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());

		loadCSVButton.setText("Cargar CSV");

		calculatePiButton.setText("Calcular Pi");

		jLabel2.setText("Seed del generador aleatorio:");

		jLabel3.setText("Numero de nodos de procesamiento:");

		pointsTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pointsTextFieldActionPerformed(evt);
			}
		});

		seedTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				seedTextFieldActionPerformed(evt);
			}
		});

		jLabel4.setText("Numero de puntos aleatorios:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 425, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6)
								.addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
												.createSequentialGroup().addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(loadCSVButton, javax.swing.GroupLayout.PREFERRED_SIZE,
														105, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(pointsTextField)
																.addComponent(seedTextField,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 128,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(resultPiLabel,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(calculatePiButton,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(nodesTextField,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 128,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 300, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(50, 50, 50).addComponent(jLabel6).addGap(27, 27, 27)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(pointsTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(seedTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(nodesTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(calculatePiButton).addComponent(loadCSVButton))
						.addGap(18, 18, 18).addComponent(resultPiLabel).addContainerGap(51, Short.MAX_VALUE))));

		pack();
	}// </editor-fold>

	private void pointsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void seedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(uiiPi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(uiiPi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(uiiPi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(uiiPi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new uiiPi().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JToggleButton calculatePiButton;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JToggleButton loadCSVButton;
	private javax.swing.JTextField nodesTextField;
	private javax.swing.JTextField pointsTextField;
	private javax.swing.JLabel resultPiLabel;
	private javax.swing.JTextField seedTextField;
	// End of variables declaration

	public javax.swing.JTextField getSeed(){
		return seedTextField;
	}
	
	public javax.swing.JTextField getPoints(){
		return pointsTextField;
	}

	public javax.swing.JTextField getNodes(){
		return nodesTextField;
	}
	
	public javax.swing.JLabel getResult(){
		return resultPiLabel;
	}

	public javax.swing.JToggleButton getCalculate(){
		return  calculatePiButton;
	}

	public javax.swing.JToggleButton getLoad(){
		return  loadCSVButton;
	}

}